# Generated by Django 3.2.6 on 2021-11-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='date_ot',
            field=models.DateField(blank=True, null=True),
        ),
    ]
