# Generated by Django 3.2.6 on 2021-11-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0007_alter_overtime_date_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='date_ot',
            field=models.DateField(blank=True, null=True),
        ),
    ]
