# Generated by Django 3.2.6 on 2021-12-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0009_employee_emp_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_profile',
        ),
    ]
